# Generated by Django 2.2.7 on 2019-11-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
